project_id = "cwsyyvzupybueberirgu"

[functions.fetch-prices]
verify_jwt = false

[functions.fetch-historical-prices]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = false

[functions.fetch-asset-news]
verify_jwt = false

[functions.check-price-alerts]
verify_jwt = false

[functions.trading-assistant]
verify_jwt = false